{{- if  .Values.launchpad.enabled }}
apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}
    namespace: {{ .Values.launchpad.Namespace }}
    labels:
        app: {{ .Release.Name }}
spec:
    ports:
        - name: {{ .Release.Name }}-http
          port: 80
          protocol: TCP
          targetPort: 3000
        - name: {{ .Release.Name }}-https
          port: 443
          protocol: TCP
          targetPort: 3443
    selector:
        app: {{ .Release.Name }}
    type: NodePort
{{- end }}